### ISSUE TITLE
Allow readonly arrays on enum definitions

### ISSUE THREAD

**Issue by otaviomad** [lukeed/tschema#10]
Sometimes you want to do something like this:

```ts
const AVAILABLE_OPTIONS = ["a", "b", "c"] as const

const optionsSchema = t.enum(AVAILABLE_OPTIONS)
```

but you get the following error:

```
Argument of type 'readonly ["a", "b", "c"]' is not assignable to parameter of type 'Value[]'.
  The type 'readonly ["a", "b", "c"]' is 'readonly' and cannot be assigned to the mutable type 'Value[]'
```

Could you also allow readonly V[] on the parameter to allow this sort of usage?

**Comment by lukeed** [comment]
At the JSON Schema level, you can only attach `readOnly` to a field, so to do this, you need to define a readonly array of enum items

What you have shown is just a type assertion/override that doesn't actually translate into anything special at runtime. 

Attaching a commit w/ an example showing how to do this, and below is the intellisense to prove the inference is what you want

![Image](https://github.com/user-attachments/assets/19645663-4524-4c9d-848c-e45603f7645e)
