### ISSUE TITLE
if...then support

### ISSUE THREAD

**Issue by marcomow** [lukeed/tschema#11]
Hi! Great library!

I can't understand if `if..then` syntax is supported or not, and how to use it?

**Comment by lukeed** [comment]
HI there, thanks :)

Do you mean [this page](https://json-schema.org/understanding-json-schema/reference/conditionals)?

If so, you'd have to add the properties (eg `dependentRequired`) manually as there's no automatic helper for those.
(There may not be types for these properties, but you can still add them)

```ts
t.object({
  name: t.string(),
  credit_card: t.optional(t.number()),
  billing_address: t.optional(t.string()),
}, {
  dependentRequired: {
    credit_card: ['billing_address']
  }
})
```

**Comment by marcomow** [comment]
Thanks for the reply

No, I actually mean this syntax https://json-schema.org/understanding-json-schema/reference/conditionals#ifthenelse

**Comment by lukeed** [comment]
Ah gotcha, hadnt seen this.
It's the same answer though. There's nothing tschema does for this, but anything passed into the 2nd `object` param is kept in the final definition

**Comment by marcomow** [comment]
Ooooh I've completely missed this, and that's perfect. Thank you!!!
